# fly.toml app configuration file generated for alumnus-app on 2023-05-29T01:49:00+08:00
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = "alumnus-app"
primary_region = "sin"

[http_service]
  internal_port = 3000
  force_https = true
  auto_stop_machines = true
  auto_start_machines = true
  min_machines_running = 0
